# Generated by Django 6.0.6 on 2026-06-21 17:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('linea_numero', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estado_linea', models.CharField(choices=[('NO_INSTALADO', 'No instalado'), ('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('CANCELADO', 'Cancelado')], default='NO_INSTALADO', max_length=20)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('saldo_vencido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='cliente.cliente')),
            ],
            options={
                'ordering': ['cliente_id', 'linea_numero'],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'linea_numero'), name='unique_linea_por_cliente')],
            },
        ),
    ]
